apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    podGroup: "A"
    minAvailable: "1"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx2
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    podGroup: "A"
    minAvailable: "1"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx3
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
    